name: Test

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        CC: [gcc, clang]

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: CC=${{ matrix.CC }} make test
